name: Build and Check for Changes
on:
  pull_request:
  # Don't include any specific paths here so we always get a build that produces a status
  # check that our Branch Protection Rules can use.  Having a status check also allows us
  # to require that branches be up to date before they are merged.
jobs:
  javascript-build:
    uses: im-open/actions-mgmt/.github/workflows/reusable-build-javascript.yml@main
    with:
      default-branch: main
      node-version: 16.x
      files-with-code: 'action.yml,package.json,package-lock.json'
      folders-with-code: 'src,dist'
      build-command: 'npm run build'
      readme-location: './README.md'
      action-name: ${{ github.repository }}
